# Generated by Django 5.2 on 2025-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('event_date',),
                'indexes': [models.Index(fields=['event_date'], name='events_even_event_d_2c2da5_idx')],
            },
        ),
    ]
