# Generated by Django 5.2 on 2025-06-20 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('total', models.PositiveIntegerField(default=1)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('date_arrived', models.DateField(blank=True, default=datetime.date.today)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('Chinese', 'Chinese'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Spain', 'Spain')], max_length=50)),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Childrens', 'Children'), ('Classics', 'Classics'), ('Fantasy', 'Fantasy'), ('Fiction', 'Fiction'), ('History', 'History'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Science', 'Science'), ('Romance', 'Romance'), ('Travel', 'Travel')], max_length=50)),
                ('cover_url', models.ImageField(blank=True, upload_to='photos/')),
            ],
            options={
                'ordering': ('-year',),
                'indexes': [models.Index(fields=['year'], name='books_book_year_d303c9_idx')],
            },
        ),
    ]
