# Generated by Django 5.2 on 2025-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('art', 'Art'), ('biography', 'Biography'), ('computers', 'Computers'), ('cooking', 'Cooking'), ('economics', 'Economics'), ('education', 'Education'), ('fantasy', 'Fantasy'), ('fiction', 'Fiction'), ('health', 'Health'), ('history', 'History'), ('mystery', 'Mystery'), ('nonfiction', 'Nonfiction'), ('psychology', 'Psychology'), ('religion', 'Religion'), ('romance', 'Romance'), ('science', 'Science'), ('sports', 'Sports'), ('travel', 'Travel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)'), ('', 'Other')], max_length=50),
        ),
    ]
