# Generated by Django 5.2 on 2025-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('overdue', 'Overdue'), ('returned', 'Returned')], max_length=50),
        ),
    ]
